# Swift Build and Test CI
name: Swift Build & Test
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Xcode
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: latest-stable
            - name: Build
              run: xcodebuild -scheme Mltply -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build
            - name: Test
              run: xcodebuild test -scheme Mltply -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
